# Generated by Django 3.1.4 on 2020-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='title',
            field=models.CharField(default='Hero', max_length=100),
        ),
    ]
