# Generated by Django 3.1.5 on 2021-01-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_activities_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
